#!/bin/bash
#BSUB -q medium
#BSUB -n 8
#BSUB -M 64
#BSUB -R "rusage[mem=64]"
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/stbresnahan/scratch/Placenta_QTL/logs3
#BSUB -e /rsrch5/home/epi/stbresnahan/scratch/Placenta_QTL/logs3

source /etc/profile.d/modules.sh
module load gatk4
eval "$(/risapps/rhel8/miniforge3/24.5.0-0/bin/conda shell.bash hook)"
conda activate gatk4-4.6.2.0

GVCF_DIR=/rsrch9/home/epi/bhattacharya_lab/data/Placenta_QTL/NIGMS/genotypes/raw
GENOMICSDB_DIR=/rsrch9/home/epi/bhattacharya_lab/data/Placenta_QTL/NIGMS/GenomicsDB
REF=/rsrch5/home/epi/stbresnahan/bhattacharya_lab/data/GenomicReferences/genome/GCA_000001405.15_GRCh38_no_alt_analysis_set_cleaned_ready_for_salmon.fasta

V_ARGS=""
for GVCF in ${GVCF_DIR}/*.g.vcf.gz; do
    V_ARGS="${V_ARGS} -V ${GVCF}"
done

gatk GenomicsDBImport \
    ${V_ARGS} \
    --genomicsdb-workspace-path ${GENOMICSDB_DIR}/${CHR} \
    -L ${CHR} \
    --reader-threads 8

gatk GenotypeGVCFs \
    -R ${REF} \
    -V gendb://${GENOMICSDB_DIR}/${CHR} \
    -L ${CHR} \
    -O ${GVCF_DIR}/${CHR}.vcf.gz
