#!/bin/bash
#BSUB -q transfer
#BSUB -n 1
#BSUB -M 12
#BSUB -R "rusage[mem=12]"
#BSUB -W 2:00
#BSUB -o /rsrch5/home/epi/stbresnahan/scratch/Placenta_QTL/logs
#BSUB -e /rsrch5/home/epi/stbresnahan/scratch/Placenta_QTL/logs

source /etc/profile.d/modules.sh
module add sratoolkit

OUTPUT_DIR=/rsrch5/home/epi/bhattacharya_lab/data/mapqtl/NIEHS_RICHS/genotypes

cd ${OUTPUT_DIR}

prefetch \
  --ngc ${OUTPUT_DIR}/prj_36524_D43286.ngc \
  --cart ${OUTPUT_DIR}/cart_prj36524_202604151233.krt \
  -O ${OUTPUT_DIR}